In [ ]:
import pandas as pd

df = pd.read_csv(r"datasets\previous_attendance.csv")
df

,subject_difficulty,profile,classes_completed,classes_attended,remaining_classes,current_attendance_percent,final_attendance_actual
0,exciting,poor,1,0,29,0.000000,17
1,boring,poor,3,1,42,33.333333,23
2,normal,poor,2,0,28,0.000000,14
3,normal,poor,3,1,42,33.333333,30
4,normal,poor,3,2,42,66.666667,25
...,...,...,...,...,...,...,...
40996,exciting,average,16,13,14,81.250000,13
40997,exciting,average,16,11,14,68.750000,11
40998,exciting,poor,16,9,14,56.250000,9
40999,exciting,poor,16,10,14,62.500000,10
41000,exciting,average,16,14,14,87.500000,14

In [77]:
# One-hot encoding
df = pd.get_dummies(df, columns=["subject_difficulty", "profile"])

In [78]:
df

,classes_completed,classes_attended,remaining_classes,current_attendance_percent,final_attendance_actual,subject_difficulty_boring,subject_difficulty_exciting,subject_difficulty_normal,profile_average,profile_good,profile_poor
0,1,0,29,0.000000,17,False,True,False,False,False,True
1,3,1,42,33.333333,23,True,False,False,False,False,True
2,2,0,28,0.000000,14,False,False,True,False,False,True
3,3,1,42,33.333333,30,False,False,True,False,False,True
4,3,2,42,66.666667,25,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
40996,16,13,14,81.250000,13,False,True,False,True,False,False
40997,16,11,14,68.750000,11,False,True,False,True,False,False
40998,16,9,14,56.250000,9,False,True,False,False,False,True
40999,16,10,14,62.500000,10,False,True,False,False,False,True
41000,16,14,14,87.500000,14,False,True,False,True,False,False

In [86]:
X

,classes_completed,classes_attended,remaining_classes,current_attendance_percent,subject_difficulty_boring,subject_difficulty_exciting,subject_difficulty_normal,profile_average,profile_good,profile_poor
0,1,0,29,0.000000,False,True,False,False,False,True
1,3,1,42,33.333333,True,False,False,False,False,True
2,2,0,28,0.000000,False,False,True,False,False,True
3,3,1,42,33.333333,False,False,True,False,False,True
4,3,2,42,66.666667,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
40996,16,13,14,81.250000,False,True,False,True,False,False
40997,16,11,14,68.750000,False,True,False,True,False,False
40998,16,9,14,56.250000,False,True,False,False,False,True
40999,16,10,14,62.500000,False,True,False,False,False,True
41000,16,14,14,87.500000,False,True,False,True,False,False

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Features
X = df.drop(columns=["final_attendance_actual"])

# Target (final attendance)
y = df["final_attendance_actual"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    max_depth=6,
    random_state=42
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [82]:
from sklearn.metrics import mean_absolute_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 2.7353219394637858
R2 Score: 0.8254212496083967

In [84]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", scores)
print("Average R2:", scores.mean())

Cross-validation R2 scores: [0.53684793 0.54143633 0.67180683 0.71966105 0.7275735 ]
Average R2: 0.6394651276959677

In [83]:
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

print("Train R2:", train_score)
print("Test R2:", test_score)

Train R2: 0.8334879592287971
Test R2: 0.8254212496083967

In [ ]:
import joblib

# Save model
# joblib.dump(model, "attendance_model.pkl")

In [4]:
model=joblib.load(r"D:\my_projects\ASPAS\attendance_model.pkl")
model = joblib.load(r"D:\my_projects\ASPAS\attendance_model.pkl")
X_t = [[
    40,   # classes_completed
    30,   # classes_attended
    10,   # remaining_classes
    75.0, # current_attendance_percent
    1,    # subject_difficulty_exciting
    0,    # subject_difficulty_normal
    0,    # subject_difficulty_boring
    0,    # profile_good
    1,    # profile_average
    0     # profile_poor
]]
predictions = model.predict(X_t)

d:\my_projects\ASPAS\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [5]:
predictions

array([36.354765])